### ISSUE TITLE
yarn install issue

### ISSUE THREAD

**Issue by rhz** [Asatelit/pwa-pos-terminal#20]
Hello. I'm running `yarn install` on a fresh node install and I get the following error while it's installing `node-sass`.
```
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/X/code/typescript/pwa-pos-terminal/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/X/.node-gyp/21.6.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/X/.node-gyp/21.6.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/X/.node-gyp/21.6.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/X/code/typescript/pwa-pos-terminal/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
    None)
  File "/home/X/.node-gyp/21.6.2/include/node/common.gypi", line 1
    incremental linking
                      ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.7.6-arch1-1
gyp ERR! command "/home/X/.nvm/versions/node/v21.6.2/bin/node" "/home/X/code/typescript/pwa-pos-terminal/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/X/code/typescript/pwa-pos-terminal/node_modules/node-sass
gyp ERR! node -v v21.6.2
gyp ERR! node-gyp -v v3.8.0
```
To install node I used `nvm install node`. That installed node version `21.6.2`.

**Comment by Asatelit** [comment]
Try to switch to Node.js v12.22.1 with Node Version Manager (nvm) and install NPM packages using yarn.
